/**
 * Libelles lisibles des actions du journal d'audit. Une action inconnue est
 * affichee telle quelle (jamais masquee).
 */
const LABELS: Record<string, string> = {
  "organization.bootstrap": "Organisation créée",
  "auth.login.succeeded": "Connexion",
  "auth.logout.succeeded": "Déconnexion",
  "crm.lead.created": "Prospect créé",
  "crm.lead.converted": "Prospect converti en opportunité",
  "crm.opportunity.stage_changed": "Opportunité déplacée dans le pipeline",
  "estimation.study.created": "Étude créée",
  "estimation.study.ready": "Étude prête pour chiffrage",
  "estimation.dqe.created": "DQE créé",
  "estimation.dqe.finalized": "DQE finalisé",
  "sales.quote.created": "Devis créé",
  "sales.quote.submitted": "Devis soumis",
  "sales.quote.accepted": "Devis accepté",
  "sales.quote.rejected": "Devis rejeté",
  "sales.contract.created": "Contrat créé",
  "auth.password.changed": "Mot de passe modifié",
  "auth.mfa.enabled": "Double authentification activée",
  "auth.mfa.disabled": "Double authentification désactivée",
  "auth.mfa.failed": "Code MFA invalide",
  "auth.login.failed": "Échec de connexion",
  "core.user.created": "Utilisateur créé",
  "core.user.updated": "Utilisateur modifié",
  "core.role.created": "Rôle créé",
  "core.role.permissions_changed": "Permissions d'un rôle modifiées",
  "core.role.deleted": "Rôle supprimé",
  "core.company.created": "Entreprise créée",
  "projects.project.created": "Projet créé",
  "projects.project.status_changed": "Statut de projet modifié",
  "projects.wbs.created": "Élément WBS ajouté",
  "projects.budget.line_added": "Ligne budgétaire ajoutée",
  "projects.budget.line_removed": "Ligne budgétaire supprimée",
  "projects.budget.baselined": "Baseline budgétaire figée",
  "projects.changeorder.requested": "Avenant demandé",
  "projects.changeorder.approved": "Avenant approuvé",
  "projects.changeorder.rejected": "Avenant rejeté",
  "projects.task.created": "Tâche créée",
  "projects.task.status_changed": "Statut de tâche modifié",
  "projects.milestone.created": "Jalon ajouté",
  "projects.milestone.achieved": "Jalon atteint",
  "projects.risk.created": "Risque enregistré",
  "projects.risk.updated": "Risque mis à jour",
  "procurement.supplier.created": "Fournisseur créé",
  "procurement.supplier.updated": "Fournisseur modifié",
  "procurement.supplier.evaluated": "Fournisseur évalué",
  "procurement.request.created": "Demande d'achat créée",
  "procurement.request.submitted": "Demande d'achat soumise",
  "procurement.request.approved": "Demande d'achat approuvée",
  "procurement.request.rejected": "Demande d'achat rejetée",
  "procurement.quote.recorded": "Offre fournisseur enregistrée",
  "procurement.order.created": "Commande créée",
  "procurement.order.issued": "Commande émise",
  "procurement.order.cancelled": "Commande annulée",
  "procurement.receipt.created": "Réception enregistrée",
  "inventory.item.created": "Article créé",
  "inventory.item.updated": "Article modifié",
  "inventory.warehouse.created": "Magasin créé",
  "inventory.issue.posted": "Sortie de stock vers chantier",
  "inventory.return.posted": "Retour de chantier en stock",
  "inventory.transfer.posted": "Transfert entre magasins",
  "inventory.adjustment.posted": "Ajustement de stock",
  "inventory.count.opened": "Inventaire ouvert",
  "inventory.count.closed": "Inventaire clôturé",
  "finance.taxrate.created": "Taux de taxe créé",
  "finance.bank.created": "Compte de trésorerie créé",
  "finance.invoice.drafted": "Facture client préparée",
  "finance.invoice.issued": "Facture client émise",
  "finance.invoice.cancelled": "Brouillon de facture annulé",
  "finance.payable.recorded": "Facture fournisseur enregistrée",
  "finance.payable.approved": "Facture fournisseur validée",
  "finance.payable.rejected": "Facture fournisseur rejetée",
  "finance.payment.received": "Encaissement client",
  "finance.payment.sent": "Paiement fournisseur",
  "hr.department.created": "Département créé",
  "hr.employee.created": "Employé enregistré",
  "hr.employee.updated": "Fiche employé modifiée",
  "hr.skill.recorded": "Compétence / habilitation enregistrée",
  "hr.attendance.recorded": "Pointage enregistré",
  "hr.timesheet.created": "Feuille de temps ouverte",
  "hr.timesheet.edited": "Feuille de temps saisie",
  "hr.timesheet.submitted": "Feuille de temps soumise",
  "hr.timesheet.validated": "Feuille de temps validée",
  "hr.timesheet.rejected": "Feuille de temps rejetée",
  "hr.leave.requested": "Congé demandé",
  "hr.leave.approved": "Congé approuvé",
  "hr.leave.rejected": "Congé refusé",
  "hr.leave.cancelled": "Congé annulé",
  "hr.payroll.prepared": "Paie préparée",
  "hr.payroll.adjusted": "Élément variable de paie saisi",
  "hr.payroll.closed": "Paie clôturée",
  "documents.file.uploaded": "Fichier déposé",
  "documents.folder.created": "Dossier GED créé",
  "documents.document.created": "Document créé",
  "documents.version.added": "Nouvelle révision déposée",
  "documents.version.submitted": "Révision soumise au visa",
  "documents.version.approved": "Révision approuvée",
  "documents.version.rejected": "Révision refusée",
  "documents.document.archived": "Document archivé",
  "field.zone.created": "Zone de chantier créée",
  "field.log.created": "Journal de chantier créé",
  "field.log.updated": "Journal de chantier complété",
  "field.log.signed": "Journal de chantier signé",
  "field.issue.created": "Réserve créée",
  "field.evidence.recorded": "Preuve horodatée enregistrée",
  "field.issue.correction_submitted": "Correction de réserve déclarée",
  "field.issue.reopened": "Correction de réserve refusée",
  "field.issue.closed": "Réserve levée",
  "qhse.template.created": "Checklist QHSE créée",
  "qhse.inspection.planned": "Inspection planifiée",
  "qhse.inspection.item_answered": "Point d'inspection renseigné",
  "qhse.inspection.completed": "Inspection clôturée",
  "qhse.finding.created": "Non-conformité ouverte",
  "qhse.finding.closed": "Non-conformité clôturée",
  "qhse.action.created": "Action corrective définie",
  "qhse.action.completed": "Action corrective réalisée",
  "qhse.action.verified": "Action corrective vérifiée",
  "qhse.action.rejected": "Action corrective refusée",
  "qhse.incident.reported": "Incident de sécurité déclaré",
  "qhse.incident.investigated": "Incident analysé",
  "qhse.incident.closed": "Incident clôturé",
  "qhse.permit.requested": "Permis de travail demandé",
  "qhse.permit.approved": "Permis de travail délivré",
  "qhse.permit.rejected": "Permis de travail refusé",
  "qhse.permit.closed": "Permis de travail clôturé",
  "qhse.toolbox.recorded": "Quart d'heure sécurité enregistré",
  "mep.system.created": "Système technique créé",
  "mep.equipment.created": "Équipement MEP créé",
  "mep.equipment.updated": "Équipement MEP modifié",
  "mep.calculation.created": "Note de calcul créée",
  "mep.calculation.revised": "Note de calcul révisée",
  "mep.calculation.validated": "Note de calcul validée",
  "commissioning.activity.created": "Mise en service ouverte",
  "commissioning.test.recorded": "Fiche d'essai enregistrée",
  "commissioning.punch.corrected": "Anomalie de mise en service corrigée",
  "commissioning.activity.accepted": "Équipement réceptionné",
  "commissioning.activity.handed_over": "Installation remise au client (DOE)",
  "bim.model.created": "Maquette BIM créée",
  "bim.version.imported": "Version IFC importée (empreinte vérifiée)",
  "bim.version.approved": "Version de maquette approuvée",
  "bim.version.rejected": "Version de maquette refusée",
  "bim.equipment.bound": "Équipement lié à un élément BIM",
  "bim.clash.created": "Conflit de synthèse créé",
  "bim.clash.proposed": "Résolution de conflit proposée",
  "bim.clash.resolved": "Conflit de synthèse résolu",
  "bim.clash.reopened": "Résolution de conflit refusée",
  "assets.asset.created": "Passeport d'actif créé",
  "assets.asset.updated": "Actif modifié",
  "assets.plan.created": "Plan préventif créé",
  "assets.plan.generated": "OT préventifs générés",
  "assets.ticket.created": "Ticket de maintenance signalé",
  "assets.ticket.converted": "Ticket converti en OT correctif",
  "assets.ticket.rejected": "Ticket de maintenance rejeté",
  "assets.workorder.started": "Ordre de travail démarré",
  "assets.workorder.labor": "Temps d'intervention saisi",
  "assets.workorder.part": "Pièce consommée sur OT",
  "assets.workorder.completed": "Ordre de travail clôturé",
  "assets.workorder.cancelled": "Ordre de travail annulé",
  "smart.building.created": "Bâtiment GTB créé",
  "smart.gateway.created": "Passerelle GTB créée (jeton émis)",
  "smart.gateway.updated": "Passerelle GTB modifiée",
  "smart.gateway.token_rotated": "Jeton de passerelle renouvelé",
  "smart.point.created": "Point de télémétrie créé",
  "smart.point.updated": "Point de télémétrie modifié",
  "smart.rule.created": "Règle d'alarme créée",
  "smart.rule.updated": "Règle d'alarme modifiée",
  "smart.alarm.acknowledged": "Alarme technique acquittée",
  "smart.setpoint.requested": "Consigne demandée",
  "smart.setpoint.cancelled": "Consigne annulée",
  "smart.setpoint.acknowledged": "Consigne acquittée par la passerelle",
  "smart.setpoint.failed": "Consigne refusée par la passerelle",
  "smart.test.recorded": "Essai réel de communication attesté",
  "smart.building.updated": "Bâtiment GTB modifié",
  "energy.meter.created": "Compteur d'énergie créé",
  "energy.meter.updated": "Compteur d'énergie modifié",
  "energy.intervals.imported": "Relevés d'énergie importés",
  "energy.tariff.created": "Tarif d'énergie enregistré",
  "energy.rule.created": "Règle d'alerte énergie créée",
  "energy.rule.updated": "Règle d'alerte énergie modifiée",
  "energy.alert.acknowledged": "Alerte énergie acquittée",
  "energy.storage.created": "Stockage d'énergie déclaré",
  "fleet.vehicle.created": "Véhicule / engin mis au parc",
  "fleet.vehicle.status": "État de véhicule modifié",
  "fleet.reading.recorded": "Relevé compteur enregistré",
  "fleet.document.recorded": "Pièce réglementaire enregistrée",
  "fleet.assignment.opened": "Véhicule affecté",
  "fleet.assignment.closed": "Véhicule restitué",
  "fleet.fuel.recorded": "Plein de carburant enregistré",
  "fleet.incident.reported": "Incident de parc déclaré",
  "fleet.incident.closed": "Incident de parc clos",
  "subcontracting.subcontractor.created": "Sous-traitant enregistré",
  "subcontracting.document.recorded": "Pièce de vigilance enregistrée",
  "subcontracting.subcontractor.qualified": "Sous-traitant qualifié",
  "subcontracting.subcontractor.suspended": "Sous-traitant suspendu",
  "subcontracting.package.created": "Lot de sous-traitance confié",
  "subcontracting.package.closed": "Lot de sous-traitance clos",
  "subcontracting.statement.prepared": "Situation de sous-traitance préparée",
  "subcontracting.statement.approved": "Situation de sous-traitance approuvée",
  "subcontracting.statement.rejected": "Situation de sous-traitance rejetée",
  "subcontracting.statement.invoiced": "Facture de situation enregistrée",
  "subcontracting.retention.released": "Retenue de garantie libérée",
  "portal.principal.invited": "Accès portail invité",
  "portal.principal.reinvited": "Invitation portail renouvelée",
  "portal.principal.activated": "Accès portail activé (par la personne invitée)",
  "portal.principal.active": "Accès portail réactivé",
  "portal.principal.suspended": "Accès portail suspendu",
  "portal.principal.revoked": "Accès portail révoqué",
  "portal.grant.created": "Ressource exposée sur un portail",
  "portal.grant.revoked": "Exposition portail retirée",
  "portal.session.opened": "Connexion au portail",
  "portal.document.downloaded": "Document téléchargé depuis le portail",
  "portal.order.acknowledged": "Commande accusée par le fournisseur (portail)",
  "workflow.definition.created": "Workflow créé (nouvelle version)",
  "workflow.definition.activated": "Version de workflow activée",
  "workflow.definition.deactivated": "Workflow désactivé",
  "workflow.approval.requested": "Approbation de workflow requise",
  "workflow.approval.approved": "Approbation de workflow accordée",
  "workflow.approval.rejected": "Approbation de workflow refusée",
  "workflow.approval.escalated": "Approbation de workflow escaladée (délai dépassé)",
  "workflow.webhook.retried": "Webhook relancé manuellement",
  "analytics.snapshot.captured": "Instantané analytique figé",
  "analytics.dashboard.created": "Tableau de bord analytique créé",
  "analytics.dashboard.updated": "Tableau de bord analytique modifié",
  "analytics.dashboard.deleted": "Tableau de bord analytique supprimé",
  "integrations.apikey.issued": "Clé d'API émise",
  "integrations.apikey.revoked": "Clé d'API révoquée",
  "integrations.api.lead.created": "Prospect créé par l'API publique",
  "integrations.inbound.created": "Webhook entrant créé",
  "integrations.inbound.activated": "Webhook entrant activé",
  "integrations.inbound.deactivated": "Webhook entrant désactivé",
  "integrations.inbound.lead.created": "Prospect reçu par webhook entrant",
};

export function describeAudit(action: string): string {
  return LABELS[action] ?? action;
}

export function registerAuditLabels(labels: Record<string, string>): void {
  Object.assign(LABELS, labels);
}
