/**
 * Libelles lisibles des actions du journal d'audit. Une action inconnue est
 * affichee telle quelle (jamais masquee).
 */
const LABELS: Record<string, string> = {
  "organization.bootstrap": "Organisation créée",
  "auth.login.succeeded": "Connexion",
  "auth.logout.succeeded": "Déconnexion",
  "crm.lead.created": "Prospect créé",
  "crm.lead.converted": "Prospect converti en opportunité",
  "crm.opportunity.stage_changed": "Opportunité déplacée dans le pipeline",
  "estimation.study.created": "Étude créée",
  "estimation.study.ready": "Étude prête pour chiffrage",
  "estimation.dqe.created": "DQE créé",
  "estimation.dqe.finalized": "DQE finalisé",
  "sales.quote.created": "Devis créé",
  "sales.quote.submitted": "Devis soumis",
  "sales.quote.accepted": "Devis accepté",
  "sales.quote.rejected": "Devis rejeté",
  "sales.contract.created": "Contrat créé",
  "auth.password.changed": "Mot de passe modifié",
  "auth.mfa.enabled": "Double authentification activée",
  "auth.mfa.disabled": "Double authentification désactivée",
  "auth.mfa.failed": "Code MFA invalide",
  "auth.login.failed": "Échec de connexion",
  "core.user.created": "Utilisateur créé",
  "core.user.updated": "Utilisateur modifié",
  "core.role.created": "Rôle créé",
  "core.role.permissions_changed": "Permissions d'un rôle modifiées",
  "core.role.deleted": "Rôle supprimé",
  "core.company.created": "Entreprise créée",
  "projects.project.created": "Projet créé",
  "projects.project.status_changed": "Statut de projet modifié",
  "projects.wbs.created": "Élément WBS ajouté",
  "projects.budget.line_added": "Ligne budgétaire ajoutée",
  "projects.budget.line_removed": "Ligne budgétaire supprimée",
  "projects.budget.baselined": "Baseline budgétaire figée",
  "projects.changeorder.requested": "Avenant demandé",
  "projects.changeorder.approved": "Avenant approuvé",
  "projects.changeorder.rejected": "Avenant rejeté",
  "projects.task.created": "Tâche créée",
  "projects.task.status_changed": "Statut de tâche modifié",
  "projects.milestone.created": "Jalon ajouté",
  "projects.milestone.achieved": "Jalon atteint",
  "projects.risk.created": "Risque enregistré",
  "projects.risk.updated": "Risque mis à jour",
  "procurement.supplier.created": "Fournisseur créé",
  "procurement.supplier.updated": "Fournisseur modifié",
  "procurement.supplier.evaluated": "Fournisseur évalué",
  "procurement.request.created": "Demande d'achat créée",
  "procurement.request.submitted": "Demande d'achat soumise",
  "procurement.request.approved": "Demande d'achat approuvée",
  "procurement.request.rejected": "Demande d'achat rejetée",
  "procurement.quote.recorded": "Offre fournisseur enregistrée",
  "procurement.order.created": "Commande créée",
  "procurement.order.issued": "Commande émise",
  "procurement.order.cancelled": "Commande annulée",
  "procurement.receipt.created": "Réception enregistrée",
  "inventory.item.created": "Article créé",
  "inventory.item.updated": "Article modifié",
  "inventory.warehouse.created": "Magasin créé",
  "inventory.issue.posted": "Sortie de stock vers chantier",
  "inventory.return.posted": "Retour de chantier en stock",
  "inventory.transfer.posted": "Transfert entre magasins",
  "inventory.adjustment.posted": "Ajustement de stock",
  "inventory.count.opened": "Inventaire ouvert",
  "inventory.count.closed": "Inventaire clôturé",
  "finance.taxrate.created": "Taux de taxe créé",
  "finance.bank.created": "Compte de trésorerie créé",
  "finance.invoice.drafted": "Facture client préparée",
  "finance.invoice.issued": "Facture client émise",
  "finance.invoice.cancelled": "Brouillon de facture annulé",
  "finance.payable.recorded": "Facture fournisseur enregistrée",
  "finance.payable.approved": "Facture fournisseur validée",
  "finance.payable.rejected": "Facture fournisseur rejetée",
  "finance.payment.received": "Encaissement client",
  "finance.payment.sent": "Paiement fournisseur",
};

export function describeAudit(action: string): string {
  return LABELS[action] ?? action;
}

export function registerAuditLabels(labels: Record<string, string>): void {
  Object.assign(LABELS, labels);
}
