import { expect, test } from "@playwright/test";

test.describe("Correction des études et DQE", () => {
  test.use({ storageState: { cookies: [], origins: [] } });
  test("corriger et supprimer avant validation, puis conserver le document figé", async ({ page }) => {
    const unique = Date.now().toString(36);
    const signup = await page.request.post("/api/v1/auth/register-organization", { data: { organizationName: `Estimation ${unique}`, organizationSlug: `estimation-${unique}`, companyName: "Entreprise Estimation", ownerFullName: "Administrateur Estimation", ownerEmail: `estimation-${unique}@axora-erp24.local`, ownerPassword: "Qualification2026!Axora" } });
    expect(signup.status()).toBe(201);
    const leadResponse = await page.request.post("/api/v1/crm/leads", { data: { companyName: "Client Estimation", contactName: "Contact Estimation" } });
    expect(leadResponse.ok()).toBeTruthy();
    const lead = await leadResponse.json() as { id: string };
    const converted = await page.request.post(`/api/v1/crm/leads/${lead.id}/convert`, { data: { amount: "1000.00", currency: "EUR" } });
    expect(converted.ok()).toBeTruthy();
    const opportunity = await converted.json() as { id: string };
    const studyResponse = await page.request.post("/api/v1/estimation/studies", { data: { opportunityId: opportunity.id, code: "ETU-DRAFT", title: "Étude Qualification", objective: "Qualifier les corrections" } });
    expect(studyResponse.ok()).toBeTruthy();
    const study = await studyResponse.json() as { id: string; version: number };
    const requirement = await page.request.post(`/api/v1/estimation/studies/${study.id}/requirements`, { data: { position: 1, category: "FACT", statement: "Exigence initiale", expectedVersion: study.version } });
    expect(requirement.ok()).toBeTruthy();
    await page.goto("/estimation");
    await page.getByRole("button", { name: "Ouvrir ETU-DRAFT", exact: true }).click();
    await page.getByRole("button", { name: "Modifier l’exigence 1" }).click();
    let dialog = page.getByRole("dialog");
    await dialog.getByRole("textbox", { name: /Énoncé de l’exigence/ }).fill("Exigence corrigée");
    await dialog.getByRole("button", { name: "Enregistrer la correction" }).click();
    await expect(dialog).toHaveCount(0);
    await expect(page.getByRole("cell", { name: "Exigence corrigée", exact: true })).toBeVisible();
    await page.getByRole("button", { name: "Valider et figer l'étude", exact: true }).click();
    await expect(page.locator(".dqe-create-form")).toBeVisible();
    const currentStudy = await (await page.request.get(`/api/v1/estimation/studies/${study.id}`)).json() as { status: string };
    expect(currentStudy.status).toBe("READY_FOR_DQE");
    const dqeResponse = await page.request.post("/api/v1/estimation/dqes", { data: { studyId: study.id, code: "DQE-DRAFT", title: "DQE Qualification", currency: "EUR" } });
    expect(dqeResponse.ok()).toBeTruthy();
    const dqe = await dqeResponse.json() as { id: string; version: number };
    const added = await page.request.post(`/api/v1/estimation/dqes/${dqe.id}/lines`, { data: { position: 1, designation: "Ouvrage initial", unitCode: "m3", quantity: "2.000000", unitPrice: "10.000000", expectedVersion: dqe.version } });
    expect(added.ok()).toBeTruthy();
    await page.reload();
    await page.getByRole("button", { name: "Ouvrir DQE-DRAFT", exact: true }).click();
    await page.getByRole("button", { name: "Modifier la ligne 1" }).click();
    dialog = page.getByRole("dialog");
    await dialog.getByRole("textbox", { name: /Quantité/ }).fill("3.123456");
    await dialog.getByRole("textbox", { name: /Prix unitaire/ }).fill("12.000000");
    await dialog.getByRole("button", { name: "Enregistrer la correction" }).click();
    await expect(dialog).toHaveCount(0);
    await expect(page.locator(".dqe-total")).toContainText("37.481472");
    await page.getByRole("button", { name: "Supprimer la ligne 1" }).click();
    dialog = page.getByRole("dialog");
    await dialog.getByRole("button", { name: "Supprimer", exact: true }).click();
    await expect(dialog).toHaveCount(0);
    await expect(page.locator(".dqe-total")).toContainText("0.000000");
    await page.locator("#line-position").fill("2");
    await page.locator("#line-designation").fill("Ouvrage final");
    await page.locator("#line-unit").fill("m3");
    await page.locator("#line-quantity").fill("2.000000");
    await page.locator("#line-unit-price").fill("10.000000");
    await page.getByRole("button", { name: "Ajouter la ligne", exact: true }).click();
    await expect(page.getByRole("cell", { name: "Ouvrage final", exact: true })).toBeVisible();
    await expect(page.locator("#line-position")).toHaveValue("3");
    await page.getByRole("button", { name: "Finaliser et figer le DQE", exact: true }).click();
    await expect(page.locator(".dqe-total")).toContainText("Finalisé");
    await expect(page.getByRole("button", { name: "Modifier la ligne 2" })).toHaveCount(0);
    const snapshot = await (await page.request.get(`/api/v1/estimation/dqes/${dqe.id}`)).json() as { lines: Array<{ unitPrice: string }>; subtotal: string };
    expect(snapshot.subtotal).toBe("20.000000");
    expect(snapshot.lines[0]!.unitPrice).toBe("10.000000");
  });
});
