import AxeBuilder from "@axe-core/playwright";
import { expect, test } from "@playwright/test";

test.describe("Première organisation et parcours commercial", () => {
  test.use({ storageState: { cookies: [], origins: [] } });
  test("créer une organisation puis gérer un client, un contact, une opportunité et une activité", async ({ page }) => {
    const unique = Date.now().toString(36);
    await page.goto("/register");
    await page.getByRole("textbox", { name: /Nom de l’organisation/ }).fill(`Qualification ${unique}`);
    await page.getByRole("textbox", { name: /Première entreprise/ }).fill(`Entreprise ${unique}`);
    await page.getByRole("textbox", { name: /Votre nom complet/ }).fill("Administrateur Qualification");
    await page.getByRole("textbox", { name: /Adresse e-mail professionnelle/ }).fill(`qualification-${unique}@axora-erp24.local`);
    await page.locator("#ownerPassword").fill("Qualification2026!Axora");
    await page.locator("#confirmation").fill("Qualification2026!Axora");
    const creation = page.waitForResponse(r => r.url().includes("/auth/register-organization") && r.request().method() === "POST");
    await page.getByRole("button", { name: "Créer mon organisation" }).click();
    expect((await creation).status()).toBe(201);
    await expect(page).toHaveURL(/\/$/);
    await page.goto("/crm");
    await expect(page.getByRole("tab")).toHaveCount(6);
    await page.getByRole("tab", { name: "Comptes", exact: true }).click();
    await page.getByRole("button", { name: "Nouveau compte" }).click();
    let dialog = page.getByRole("dialog");
    await dialog.getByRole("textbox", { name: /Nom de l’entreprise/ }).fill("Client Qualification");
    await dialog.getByRole("textbox", { name: "Courriel" }).fill("client@example.com");
    await dialog.getByRole("button", { name: "Enregistrer" }).click();
    await expect(dialog).toHaveCount(0);
    await expect(page.getByRole("cell", { name: "Client Qualification", exact: true })).toBeVisible();
    await page.getByRole("button", { name: "Modifier Client Qualification" }).click();
    dialog = page.getByRole("dialog");
    await dialog.getByRole("textbox", { name: "Ville" }).fill("Lagos");
    await dialog.getByRole("button", { name: "Enregistrer" }).click();
    await expect(dialog).toHaveCount(0);
    await expect(page.getByRole("cell", { name: /Lagos/ })).toBeVisible();
    await page.getByRole("tab", { name: "Contacts", exact: true }).click();
    await page.getByRole("button", { name: "Nouveau contact" }).click();
    dialog = page.getByRole("dialog");
    await dialog.getByRole("textbox", { name: /Nom complet/ }).fill("Contact Qualification");
    await dialog.getByRole("combobox", { name: "Compte associé" }).selectOption({ label: "Client Qualification" });
    await dialog.getByLabel("Contact principal du compte").check();
    await dialog.getByRole("button", { name: "Enregistrer" }).click();
    await expect(dialog).toHaveCount(0);
    await page.getByRole("tab", { name: "Prospects", exact: true }).click();
    await page.locator("#lead-company").fill("Client Qualification");
    await page.locator("#lead-contact").fill("Contact Qualification");
    await page.getByRole("button", { name: "Ajouter", exact: true }).click();
    await page.getByRole("button", { name: "Convertir Client Qualification" }).click();
    dialog = page.getByRole("dialog");
    await dialog.getByRole("textbox", { name: "Montant", exact: true }).fill("12500.50");
    await dialog.getByRole("textbox", { name: "Devise", exact: true }).fill("EUR");
    await dialog.getByRole("combobox", { name: "Compte client" }).selectOption({ label: "Client Qualification" });
    await dialog.getByRole("combobox", { name: "Contact du compte" }).selectOption({ label: "Contact Qualification" });
    await dialog.getByRole("button", { name: "Créer l’opportunité" }).click();
    await expect(dialog).toHaveCount(0);
    await expect(page.getByRole("tab", { name: "Opportunités", exact: true })).toHaveAttribute("aria-selected", "true");
    await expect(page.getByRole("cell", { name: /12.*500,50 EUR/ })).toBeVisible();
    await page.getByRole("tab", { name: "Activités", exact: true }).click();
    await page.getByRole("button", { name: "Nouvelle activité" }).click();
    dialog = page.getByRole("dialog");
    await dialog.getByRole("combobox", { name: "Type de fiche liée" }).selectOption("Opportunity");
    await dialog.getByRole("combobox", { name: "Fiche liée", exact: true }).selectOption({ label: "Client Qualification" });
    await dialog.getByRole("textbox", { name: "Objet" }).fill("Prise de contact");
    await dialog.getByRole("textbox", { name: "Contenu" }).fill("Réunion de lancement à planifier.");
    const axe = await new AxeBuilder({ page }).withTags(["wcag2a", "wcag2aa", "wcag21aa", "wcag22aa"]).analyze();
    expect(axe.violations.map(v => v.id)).toEqual([]);
    await dialog.getByRole("button", { name: "Enregistrer" }).click();
    await expect(dialog).toHaveCount(0);
    await expect(page.getByRole("cell", { name: /Prise de contact/ })).toBeVisible();
  });
});
