import React from "react";
import type { CommissioningActivityView, ContractView, PurchaseOrderView, PurchaseRequestView, QuoteView, SiteDailyLogView, StockMovementView, TimesheetView } from "@axora24/contracts";
import type { BusinessPrintKind } from "./business-print-link";
import { formatDate, formatDateTime, formatMoney, formatQuantity } from "../lib/format";
import { ORDER_STATUS_LABEL, REQUEST_STATUS_LABEL } from "../lib/modules/procurement";
import { TIMESHEET_STATUS_LABEL } from "../lib/modules/hr";
import { STAGE_LABEL, TEST_KIND_LABEL } from "../lib/modules/commissioning";

export type BusinessDocument = QuoteView | ContractView | PurchaseRequestView | PurchaseOrderView | SiteDailyLogView | CommissioningActivityView | TimesheetView | StockMovementView;
function Fields({ values }: { values: Array<[string, React.ReactNode]> }): React.ReactElement { return <dl className="print-fields">{values.map(([label, value]) => <div key={label}><dt>{label}</dt><dd>{value ?? "—"}</dd></div>)}</dl>; }
function Paragraph({ title, value }: { title: string; value: string | null | undefined }): React.ReactNode { return value ? <section><h2>{title}</h2><p className="print-paragraph">{value}</p></section> : null; }
function CommercialLines({ lines, currency }: { lines: QuoteView["lines"]; currency: string }): React.ReactElement { return <table><caption>Lignes du document</caption><thead><tr>{["Désignation", "Unité", "Quantité", "Prix unitaire", "Total"].map(label => <th key={label} scope="col">{label}</th>)}</tr></thead><tbody>{lines.map(line => <tr key={line.id}><td>{line.designation}{line.reference && <small> · {line.reference}</small>}</td><td>{line.unitCode}</td><td>{formatQuantity(line.quantity, 6)}</td><td>{`${formatQuantity(line.unitPrice, 6)} ${currency}`}</td><td>{formatMoney(line.lineTotal, currency)}</td></tr>)}</tbody></table>; }

export function businessPrintMetadata(kind: BusinessPrintKind, document: BusinessDocument, receiptId: string | null = null): { title: string; reference: string } | null {
  if (kind === "goods-receipts") { const receipt = (document as PurchaseOrderView).receipts.find(item => item.id === receiptId); return receipt ? { title: "Bon de réception", reference: receipt.code } : null; }
  if (kind === "daily-logs") { const log = document as SiteDailyLogView; return { title: "Rapport journalier de chantier", reference: [log.projectCode, formatDate(log.logDate)].filter(Boolean).join(" · ") }; }
  if (kind === "timesheets") { const sheet = document as TimesheetView; return { title: "Feuille de temps", reference: `${sheet.employeeName} · semaine du ${formatDate(sheet.weekStart)}` }; }
  if (kind === "commissioning") { const activity = document as CommissioningActivityView; return { title: ["ACCEPTED", "HANDED_OVER"].includes(activity.status) ? "Procès-verbal de réception" : "Compte rendu de mise en service", reference: activity.code }; }
  if (kind === "stock-movements") { const movement = document as StockMovementView; return { title: movement.type === "ISSUE" ? "Bon de sortie de stock" : movement.type === "RETURN" ? "Bon de retour de stock" : "Mouvement de stock", reference: movement.reference ?? `${movement.itemCode} · ${formatDateTime(movement.createdAt)}` }; }
  return { title: kind === "quotes" ? "Devis" : kind === "contracts" ? "Contrat" : kind === "purchase-requests" ? "Demande d’achat" : "Bon de commande", reference: (document as QuoteView).code };
}

export function BusinessPrintContent({ kind, document, receiptId }: { kind: BusinessPrintKind; document: BusinessDocument; receiptId?: string | null }): React.ReactElement {
  if (kind === "quotes" || kind === "contracts") {
    const commercial = document as QuoteView | ContractView;
    const isQuote = kind === "quotes";
    const quote = document as QuoteView;
    const status = isQuote ? ({ DRAFT: "Brouillon", SUBMITTED: "Soumis", ACCEPTED: "Accepté", REJECTED: "Rejeté" })[quote.status] : commercial.status === "ACTIVE" ? "Actif" : "Archivé";
    return <><p className="print-document-status">{status}{isQuote && quote.status === "DRAFT" ? " — document non soumis" : ""}</p><Fields values={[["Objet", commercial.title], ["Création", formatDateTime(commercial.createdAt)], ["Devise", commercial.currency], ["Document source", isQuote ? quote.source.dqeCode : (document as ContractView).source.quoteCode], ...(isQuote ? [["Version", String(quote.version)], ["Soumission", formatDateTime(quote.submittedAt)], ["Acceptation", formatDateTime(quote.acceptedAt)]] as Array<[string, React.ReactNode]> : [])]} /><CommercialLines lines={commercial.lines} currency={commercial.currency} /><p className="print-document-total">Total des lignes : {formatMoney(commercial.subtotal, commercial.currency)}</p>{isQuote && <Paragraph title="Motif du rejet" value={quote.rejectionReason} />}</>;
  }
  if (kind === "purchase-requests") {
    const request = document as PurchaseRequestView;
    return <><p className="print-document-status">{REQUEST_STATUS_LABEL[request.status]}</p><Fields values={[["Objet", request.title], ["Projet", request.projectCode], ["Demandeur", request.requestedByName], ["Besoin pour le", formatDate(request.neededBy)], ["Soumission", formatDateTime(request.submittedAt)], ["Décision", formatDateTime(request.decidedAt)]]} /><Paragraph title="Justification" value={request.justification} /><table><caption>Lignes de la demande</caption><thead><tr>{["Désignation", "Unité", "Quantité", "Prix estimatif", "Total estimatif"].map(label => <th key={label} scope="col">{label}</th>)}</tr></thead><tbody>{request.lines.map(line => <tr key={line.id}><td>{line.description}</td><td>{line.unitCode}</td><td>{formatQuantity(line.quantity, 3)}</td><td>{formatMoney(line.estimatedUnitPrice, request.currency)}</td><td>{formatMoney(line.estimatedTotal, request.currency)}</td></tr>)}</tbody></table><p className="print-document-total">Total estimatif : {formatMoney(request.estimatedTotal, request.currency)}</p><Paragraph title="Décision" value={request.decisionNote} /></>;
  }
  if (kind === "purchase-orders" || kind === "goods-receipts") {
    const order = document as PurchaseOrderView;
    if (kind === "goods-receipts") {
      const receipt = order.receipts.find(item => item.id === receiptId);
      if (!receipt) return <p>Bon de réception introuvable.</p>;
      return <><Fields values={[["Commande", order.code], ["Fournisseur", order.supplierName], ["Projet", order.projectCode], ["Réception", formatDateTime(receipt.receivedAt)], ["Réceptionné par", receipt.receivedByName]]} /><table><caption>Quantités réceptionnées</caption><thead><tr><th scope="col">Désignation</th><th scope="col">Unité</th><th scope="col">Quantité réceptionnée</th></tr></thead><tbody>{receipt.lines.map(line => { const original = order.lines.find(item => item.id === line.orderLineId); return <tr key={line.orderLineId}><td>{original?.description ?? "Ligne de commande"}</td><td>{original?.unitCode ?? "—"}</td><td>{formatQuantity(line.quantity, 3)}</td></tr>; })}</tbody></table><Paragraph title="Note de réception" value={receipt.note} /></>;
    }
    return <><p className="print-document-status">{ORDER_STATUS_LABEL[order.status]}</p><Fields values={[["Fournisseur", order.supplierName], ["Projet", order.projectCode], ["Demande d’origine", order.requestCode], ["Émission", formatDateTime(order.issuedAt)], ["Livraison attendue", formatDate(order.expectedDate)], ["Création", formatDateTime(order.createdAt)]]} /><table><caption>Lignes commandées</caption><thead><tr>{["Désignation", "Unité", "Quantité", "Prix unitaire", "Total"].map(label => <th key={label} scope="col">{label}</th>)}</tr></thead><tbody>{order.lines.map(line => <tr key={line.id}><td>{line.description}</td><td>{line.unitCode}</td><td>{formatQuantity(line.quantity, 3)}</td><td>{formatMoney(line.unitPrice, order.currency)}</td><td>{formatMoney(line.lineTotal, order.currency)}</td></tr>)}</tbody></table><p className="print-document-total">Total : {formatMoney(order.total, order.currency)}</p><Paragraph title="Annulation" value={order.cancelReason} /></>;
  }
  if (kind === "timesheets") {
    const sheet = document as TimesheetView;
    return <><p className="print-document-status">{TIMESHEET_STATUS_LABEL[sheet.status]}</p><Fields values={[["Salarié", sheet.employeeName], ["Semaine du", formatDate(sheet.weekStart)], ["Heures déclarées", `${sheet.totalHours} h`], ["Heures pointées", `${sheet.attendanceHours} h`], ["Soumise le", formatDateTime(sheet.submittedAt)], ["Décision le", formatDateTime(sheet.decidedAt)]]} /><table><caption>Heures déclarées par jour et chantier</caption><thead><tr>{["Jour", "Heures", "Projet", "Description"].map(label => <th key={label} scope="col">{label}</th>)}</tr></thead><tbody>{sheet.entries.map(line => <tr key={line.id}><td>{formatDate(line.workDate)}</td><td>{line.hours} h</td><td>{line.projectCode ?? "Hors projet"}</td><td>{line.description ?? "—"}</td></tr>)}</tbody></table><Paragraph title="Note de décision" value={sheet.decisionNote} /><p>Seules les heures validées par un autre responsable alimentent les coûts et la paie.</p></>;
  }
  if (kind === "daily-logs") {
    const log = document as SiteDailyLogView;
    return <><p className="print-document-status">{log.status === "SIGNED" ? "Signé" : "Brouillon"}</p><Fields values={[["Projet", log.projectCode], ["Date du rapport", formatDate(log.logDate)], ["Auteur", log.createdByName], ["Version", String(log.version)], ["Météo", log.weather], ["Température", log.temperature], ["Effectif déclaré", String(log.workforceCount)], ["Effectif pointé", String(log.clockedInCount)], ["Signé par", log.signedByName], ["Signature enregistrée le", formatDateTime(log.signedAt)]]} /><Paragraph title="Activités et observations" value={log.summary} /><Paragraph title="Sécurité" value={log.safetyNotes} /><h2>Matériaux sortis</h2><table><caption>Consommations enregistrées du jour</caption><thead><tr><th scope="col">Article</th><th scope="col">Quantité</th></tr></thead><tbody>{log.stockIssues.map((line, index) => <tr key={`${line.itemCode}-${index}`}><td>{line.itemCode} · {line.itemName}</td><td>{formatQuantity(line.quantity, 3)} {line.unitCode}</td></tr>)}</tbody></table>{log.evidence.length > 0 && <><h2>Preuves référencées</h2><ul>{log.evidence.map(evidence => <li key={evidence.id}>{formatDateTime(evidence.takenAt)} · {evidence.createdByName}{evidence.note ? ` · ${evidence.note}` : ""}{evidence.file ? ` · ${evidence.file.originalName}` : ""}</li>)}</ul></>}</>;
  }
  if (kind === "commissioning") {
    const activity = document as CommissioningActivityView;
    return <><p className="print-document-status">{STAGE_LABEL[activity.stage]}</p><Fields values={[["Équipement", `${activity.equipmentTag} · ${activity.equipmentName}`], ["Système", activity.systemCode], ["Projet", activity.projectCode], ["Réceptionné par", activity.acceptedByName], ["Réception le", formatDateTime(activity.acceptedAt)], ["Destinataire de la remise", activity.handoverRecipient], ["Remise le", formatDateTime(activity.handedOverAt)]]} /><Paragraph title="Procédure" value={activity.procedure} /><Paragraph title="Note de réception" value={activity.acceptanceNote} />{activity.blockers.length > 0 && <><h2>Réception bloquée</h2><ul>{activity.blockers.map((blocker, index) => <li key={index}>{blocker}</li>)}</ul></>}{activity.tests?.map(test => <section key={test.id}><h2>Essai {test.sequence} · {TEST_KIND_LABEL[test.kind]}</h2><p>{test.outcome === "PASS" ? "Conforme" : "Non conforme"} · {test.performedByName} · {formatDateTime(test.performedAt)}</p>{test.measurements.length > 0 && <table><caption>Mesures de l’essai {test.sequence}</caption><thead><tr>{["Mesure", "Minimum", "Maximum", "Valeur", "Résultat"].map(label => <th key={label} scope="col">{label}</th>)}</tr></thead><tbody>{test.measurements.map((measure, index) => <tr key={index}><td>{measure.name} ({measure.unit})</td><td>{measure.min ?? "—"}</td><td>{measure.max ?? "—"}</td><td>{measure.measured}</td><td>{measure.pass ? "Conforme" : "Non conforme"}</td></tr>)}</tbody></table>}{test.checks.length > 0 && <ul>{test.checks.map((check, index) => <li key={index}>{check.label} : {check.ok ? "Conforme" : "Non conforme"}</li>)}</ul>}<Paragraph title="Notes d’essai" value={test.notes} /></section>)}{!!activity.punchItems?.length && <><h2>Réserves et corrections</h2><ul>{activity.punchItems.map(item => <li key={item.id}>{item.description} · {item.status === "OPEN" ? "Ouverte" : item.status === "CORRECTED" ? "Corrigée" : "Clôturée"}{item.correctionNote ? ` · ${item.correctionNote}` : ""}</li>)}</ul></>}</>;
  }
  const movement = document as StockMovementView;
  return <><Fields values={[["Article", `${movement.itemCode} · ${movement.itemName}`], ["Dépôt", movement.warehouseCode], ["Projet", movement.projectCode], ["Date", formatDateTime(movement.createdAt)], ["Enregistré par", movement.createdByName], ["Variation de quantité", formatQuantity(movement.quantityDelta, 3)], ["Référence", movement.reference]]} /><Paragraph title="Motif" value={movement.reason} /><p>Ce bon reprend le mouvement enregistré dans le stock.</p></>;
}
