import { randomBytes } from "node:crypto";
import { afterAll, beforeAll, describe, expect, it } from "vitest";
import { as, createHarness, registerTenant, type Harness, type Tenant } from "./support/harness.js";
import { createStartedProject, createUserWith } from "./support/fixtures.js";
import { createCardCredential } from "../src/hr/service-card-credentials.js";

describe("Service cards, attendance evidence and explicit payroll policy", () => {
  let harness: Harness;
  let tenant: Tenant;
  let other: Tenant;
  let operator: Tenant;
  let validator: Tenant;
  let employeeId: string;
  let cardId: string;
  let qrPayload: string;
  let historicalInId: string;
  let historicalOutId: string;
  const previousKey = process.env.SERVICE_CARD_ENCRYPTION_KEY;
  const api = (scope = tenant, actor?: Tenant) => as(harness, actor ?? scope);
  beforeAll(async () => {
    process.env.SERVICE_CARD_ENCRYPTION_KEY = randomBytes(32).toString("base64");
    harness = await createHarness();
    tenant = await registerTenant(harness, "hr-operations");
    other = await registerTenant(harness, "hr-operations-other");
    operator = await createUserWith(harness, tenant, ["hr.employee.read", "hr.attendance.create", "hr.timesheet.manage"], "hr-operator");
    validator = await createUserWith(harness, tenant, ["hr.employee.read", "hr.timesheet.validate"], "hr-validator");
    const employee = await api().post("/hr/employees", { firstName: "Alice", lastName: "Evidence", jobTitle: "Technicienne", hireDate: "2026-01-01", contractType: "PERMANENT", baseSalary: "3000.00", hourlyCost: "25.00", badgeCode: "LEGACY-HR-CARD" });
    expect(employee.status).toBe(201);
    employeeId = employee.body.id;
    const historicalIn = await api().post("/hr/attendance", { employeeId, type: "IN", occurredAt: "2026-09-28T23:00:00Z" });
    const historicalOut = await api().post("/hr/attendance", { employeeId, type: "OUT", occurredAt: "2026-09-29T01:00:00Z" });
    expect([historicalIn.status, historicalOut.status]).toEqual([201, 201]);
    historicalInId = historicalIn.body.id;
    historicalOutId = historicalOut.body.id;
  });
  afterAll(async () => {
    await harness.close();
    if (previousKey === undefined) delete process.env.SERVICE_CARD_ENCRYPTION_KEY; else process.env.SERVICE_CARD_ENCRYPTION_KEY = previousKey;
  });

  it("separates card management, safe metadata and printable credentials", async () => {
    expect((await api(tenant, operator).post(`/hr/employees/${employeeId}/service-card`, {})).status).toBe(403);
    const issued = await api().post(`/hr/employees/${employeeId}/service-card`, {});
    expect(issued.status).toBe(201);
    expect(issued.body.qrPayload).toMatch(/^AXORA-CARD:v1:[A-Za-z0-9_-]{43}$/);
    expect(issued.body.qrPayload).not.toContain(employeeId);
    cardId = issued.body.card.id;
    qrPayload = issued.body.qrPayload;
    const metadata = await api(tenant, operator).get(`/hr/employees/${employeeId}/service-cards`);
    expect(metadata.status).toBe(200);
    expect(metadata.body).toHaveLength(1);
    expect(JSON.stringify(metadata.body)).not.toContain(qrPayload.slice("AXORA-CARD:v1:".length));
    expect((await api(tenant, operator).get(`/hr/employees/${employeeId}/service-card`)).status).toBe(403);
    expect((await api().get(`/hr/employees/${employeeId}/service-card`)).body.qrPayload).toBe(qrPayload);
    const employee = (await api(tenant, operator).get("/hr/employees")).body.find((item: { id: string }) => item.id === employeeId);
    expect(employee.serviceCard.status).toBe("ACTIVE");
    expect(employee.baseSalary).toBeNull();
    expect(employee.hourlyCost).toBeNull();
    const audits = await harness.prisma.auditLog.findMany({ where: { organizationId: tenant.organizationId, action: { startsWith: "hr.service_card" } } });
    expect(JSON.stringify(audits)).not.toContain(qrPayload.slice("AXORA-CARD:v1:".length));
  });
  it("records one server-timed event for concurrent retries and rejects untrusted QR identifiers", async () => {
    expect((await api(other).post("/hr/attendance/scan", { cardToken: qrPayload, type: "IN", idempotencyKey: "other-card-key" })).status).toBe(404);
    expect((await api(tenant, operator).post("/hr/attendance/scan", { badgeCode: "LEGACY-HR-CARD", source: " QR ", type: "IN" })).status).toBe(400);
    expect((await api(tenant, operator).post("/hr/attendance/scan", { cardToken: qrPayload, type: "IN", idempotencyKey: "backdated-card", occurredAt: "2026-09-01T08:00:00Z" })).status).toBe(400);
    const payload = { cardToken: qrPayload, type: "IN", idempotencyKey: "concurrent-card-in" };
    const concurrent = await Promise.all(Array.from({ length: 5 }, () => api(tenant, operator).post("/hr/attendance/scan", payload)));
    expect(concurrent.map((response) => response.status)).toEqual([201, 201, 201, 201, 201]);
    expect(new Set(concurrent.map((response) => response.body.id)).size).toBe(1);
    expect(concurrent.filter((response) => response.body.replayed === false)).toHaveLength(1);
    expect((await api(tenant, operator).post("/hr/attendance/scan", { ...payload, type: "OUT" })).status).toBe(409);
    expect((await api(tenant, operator).post("/hr/attendance/scan", { ...payload, idempotencyKey: "second-in" })).status).toBe(400);
    const out = await api(tenant, operator).post("/hr/attendance/scan", { cardToken: qrPayload, type: "OUT", idempotencyKey: "card-out" });
    expect(out.status).toBe(201);
    expect(out.body.source).toBe("QR");
    const stored = await harness.prisma.attendanceEvent.findUniqueOrThrow({ where: { id: out.body.id } });
    expect(stored.serviceCardId).toBe(cardId);
    expect(stored.occurredAt.getTime()).toBeGreaterThan(Date.now() - 60_000);
  });
  it("rotates cards, enforces revocation and checks employee status during scanning", async () => {
    const previous = qrPayload;
    const issued = await api().post(`/hr/employees/${employeeId}/service-card`, {});
    expect(issued.status).toBe(201);
    qrPayload = issued.body.qrPayload;
    cardId = issued.body.card.id;
    expect(qrPayload).not.toBe(previous);
    expect((await api(tenant, operator).post("/hr/attendance/scan", { cardToken: previous, type: "IN", idempotencyKey: "revoked-card" })).status).toBe(400);
    expect((await api().patch(`/hr/employees/${employeeId}`, { status: "SUSPENDED" })).status).toBe(200);
    expect((await api(tenant, operator).post("/hr/attendance/scan", { cardToken: qrPayload, type: "IN", idempotencyKey: "suspended-card" })).status).toBe(400);
    expect((await api().patch(`/hr/employees/${employeeId}`, { status: "ACTIVE" })).status).toBe(200);
    expect((await api().post(`/hr/service-cards/${cardId}/revoke`, { reason: "Carte perdue" })).status).toBe(201);
    expect((await api().get(`/hr/employees/${employeeId}/service-card`)).status).toBe(404);
    expect((await api(tenant, operator).post("/hr/attendance/scan", { cardToken: qrPayload, type: "IN", idempotencyKey: "lost-card" })).status).toBe(400);
    expect((await api().post(`/hr/employees/${employeeId}/service-card`, { expiresAt: "2026-01-01" })).status).toBe(400);
  });
  it("prepares drafts from closed overnight attendance and retains source facts after validation", async () => {
    expect((await api().post("/hr/attendance", { employeeId, type: "IN", occurredAt: "2026-09-28T23:00:00Z" })).status).toBe(400);
    const sheet = await api(tenant, operator).post("/hr/timesheets", { employeeId, weekStart: "2026-09-28" });
    expect(sheet.status).toBe(201);
    const imported = await api(tenant, operator).post(`/hr/timesheets/${sheet.body.id}/from-attendance`, {});
    expect(imported.status).toBe(201);
    // The later card session is real but generally rounds to zero; overnight facts remain exact.
    expect(imported.body.entries.filter((entry: { workDate: string }) => entry.workDate.startsWith("2026-09-")).map((entry: { hours: string }) => entry.hours)).toEqual(["1.00", "1.00"]);
    expect((await api(tenant, operator).post(`/hr/timesheets/${sheet.body.id}/from-attendance`, {})).status).toBe(409);
    expect((await api(tenant, operator).post(`/hr/timesheets/${sheet.body.id}/submit`)).status).toBe(201);
    expect((await api(tenant, operator).post(`/hr/timesheets/${sheet.body.id}/validate`, {})).status).toBe(403);
    expect((await api(tenant, validator).post(`/hr/timesheets/${sheet.body.id}/validate`, {})).status).toBe(201);
    const stored = await harness.prisma.timesheetEntry.findMany({ where: { timesheetId: sheet.body.id, attendanceInId: historicalInId } });
    expect(stored).toHaveLength(2);
    expect(stored.every((entry) => entry.attendanceOutId === historicalOutId)).toBe(true);
    expect((await api(tenant, validator).get(`/hr/timesheets/${sheet.body.id}`)).body.entries.every((entry: { costAmount: string | null }) => entry.costAmount === null)).toBe(true);
    expect((await api().get(`/hr/timesheets/${sheet.body.id}`)).body.entries[0].costAmount).toBe("25.00");
    expect((await api(tenant, operator).post(`/hr/timesheets/${sheet.body.id}/from-attendance`, { replaceExisting: true })).status).toBe(400);
    expect((await api(other).get(`/hr/timesheets/${sheet.body.id}`)).status).toBe(404);
  });
  it("requires explicit policy assumptions, freezes calculated wages and serializes monthly preparation", async () => {
    const initial = await api().get("/hr/payroll-policy");
    expect(initial.body).toMatchObject({ mode: "MONTHLY_BASE", version: 0, configured: false });
    expect((await api(tenant, operator).get("/hr/payroll-policy")).status).toBe(403);
    expect((await api(tenant, operator).patch("/hr/payroll-policy", { expectedVersion: 0, mode: "VALIDATED_HOURS", standardMonthlyHours: "160", overtimeCoefficient: "1.50" })).status).toBe(403);
    expect((await api().patch("/hr/payroll-policy", { expectedVersion: 0, mode: "VALIDATED_HOURS" })).status).toBe(400);
    const configured = await api().patch("/hr/payroll-policy", { expectedVersion: 0, mode: "VALIDATED_HOURS", standardMonthlyHours: "160", overtimeCoefficient: "1.50" });
    expect(configured.status).toBe(200);
    expect((await api().patch("/hr/payroll-policy", { expectedVersion: 0, mode: "MONTHLY_BASE" })).status).toBe(409);
    const results = await Promise.all([api().post("/hr/payroll", { period: "2026-09" }), api().post("/hr/payroll", { period: "2026-09" })]);
    expect(results.map((response) => response.status).sort()).toEqual([201, 409]);
    const run = results.find((response) => response.status === 201)!;
    expect(run.body.lines[0]).toMatchObject({ validatedHours: "2.00", regularHours: "2.00", overtimeHours: "0.00", automaticAmount: "37.50", grossAmount: "37.50" });
    expect(run.body.netAmount).toBeNull();
    expect(run.body.statutoryDeductions).toBe("NOT_CONFIGURED");
    expect((await api().patch("/hr/payroll-policy", { expectedVersion: configured.body.version, mode: "MONTHLY_BASE" })).status).toBe(200);
    const frozen = await api().get(`/hr/payroll/${run.body.id}`);
    expect(frozen.body.policy.mode).toBe("VALIDATED_HOURS");
    expect(frozen.body.lines[0].automaticAmount).toBe("37.50");
    const adjusted = await api().post(`/hr/payroll/${run.body.id}/adjustments`, { employeeId, amount: "10.00", label: "Prime convenue" });
    expect(adjusted.status).toBe(201);
    expect(adjusted.body.lines[0].grossAmount).toBe("47.50");
    expect((await api().post(`/hr/payroll/${run.body.id}/close`)).status).toBe(201);
    expect((await api().post(`/hr/payroll/${run.body.id}/adjustments`, { employeeId, amount: "1.00", label: "Après clôture" })).status).toBe(400);
    const monthly = await api().post("/hr/payroll", { period: "2026-08" });
    expect(monthly.status).toBe(201);
    expect(monthly.body.lines[0].automaticAmount).toBe("3000.00");
    expect(monthly.body.warnings).toEqual(expect.arrayContaining([expect.objectContaining({ code: "NO_VALIDATED_HOURS" })]));
  });
  it("enforces card, attendance-source and closed payroll invariants below the API", async () => {
    const scope = { organizationId: tenant.organizationId, companyId: tenant.companyId };
    const closed = await harness.prisma.payrollRun.findFirstOrThrow({ where: { ...scope, period: "2026-09" } });
    const line = await harness.prisma.payrollLine.findFirstOrThrow({ where: { runId: closed.id, ...scope } });
    await expect(harness.prisma.payrollRun.update({ where: { id: closed.id }, data: { status: "DRAFT" } })).rejects.toThrow();
    await expect(harness.prisma.payrollLine.update({ where: { id: line.id }, data: { grossAmount: "0.00" } })).rejects.toThrow();
    await expect(harness.prisma.payrollLine.delete({ where: { id: line.id } })).rejects.toThrow();
    await expect(harness.prisma.payrollRun.delete({ where: { id: closed.id } })).rejects.toThrow();
    const draft = await harness.prisma.payrollRun.findFirstOrThrow({ where: { ...scope, period: "2026-08" } });
    const draftLine = await harness.prisma.payrollLine.findFirstOrThrow({ where: { runId: draft.id, ...scope } });
    await expect(harness.prisma.payrollRun.update({ where: { id: draft.id }, data: { policyVersion: 99 } })).rejects.toThrow();
    await expect(harness.prisma.payrollRun.update({ where: { id: draft.id }, data: { policySnapshot: { mode: "VALIDATED_HOURS" } } })).rejects.toThrow();
    await expect(harness.prisma.payrollLine.update({ where: { id: draftLine.id }, data: { validatedHours: "744.00" } })).rejects.toThrow();
    await expect(harness.prisma.payrollLine.update({ where: { id: draftLine.id }, data: { automaticAmount: "1.00", grossAmount: "1.00" } })).rejects.toThrow();
    await expect(harness.prisma.payrollLine.update({ where: { id: draftLine.id }, data: { adjustments: "10.00", grossAmount: "0.00" } })).rejects.toThrow();
    await expect(harness.prisma.employeeServiceCard.update({ where: { id: cardId }, data: { tokenHash: randomBytes(32).toString("hex") } })).rejects.toThrow();
    await expect(harness.prisma.employeeServiceCard.delete({ where: { id: cardId } })).rejects.toThrow();
    const policy = await harness.prisma.companyPayrollPolicy.findFirstOrThrow({ where: scope });
    await expect(harness.prisma.companyPayrollPolicy.update({ where: { id: policy.id }, data: { mode: "VALIDATED_HOURS", standardMonthlyHours: null, overtimeCoefficient: null } })).rejects.toThrow();
    const secondEmployee = await api().post("/hr/employees", { firstName: "Bob", lastName: "Boundary", jobTitle: "Technicien", hireDate: "2026-01-01", contractType: "PERMANENT" });
    expect(secondEmployee.status).toBe(201);
    const sheet = await api().post("/hr/timesheets", { employeeId: secondEmployee.body.id, weekStart: "2026-09-28" });
    expect(sheet.status).toBe(201);
    await expect(harness.prisma.timesheetEntry.create({ data: { ...scope, timesheetId: sheet.body.id, workDate: new Date("2026-09-28"), hours: "1.00", attendanceInId: historicalInId, attendanceOutId: historicalOutId } })).rejects.toThrow();
    const credential = createCardCredential();
    const issuedAt = new Date(Date.now() - 2 * 86_400_000);
    const expiresAt = new Date(Date.now() - 86_400_000);
    const expired = await harness.prisma.employeeServiceCard.create({ data: { ...scope, employeeId, tokenHash: credential.tokenHash, tokenCiphertext: credential.tokenCiphertext, issuedByUserId: tenant.userId, issuedAt, expiresAt } });
    expect((await api(tenant, operator).post("/hr/attendance/scan", { cardToken: credential.qrPayload, type: "IN", idempotencyKey: "expired-card-scan" })).status).toBe(400);
    expect((await api().post(`/hr/service-cards/${expired.id}/revoke`, { reason: "Expired test card" })).status).toBe(201);
  });
  it("keeps migrated historical payroll hours unavailable instead of inventing zeroes", async () => {
    const scope = { organizationId: tenant.organizationId, companyId: tenant.companyId };
    const legacy = await harness.prisma.payrollRun.create({ data: { ...scope, period: "2026-07", currency: "USD", createdByUserId: tenant.userId } });
    await harness.prisma.payrollLine.create({ data: { ...scope, runId: legacy.id, employeeId, baseSalary: "3000.00", validatedHours: "8.00", automaticAmount: "3000.00", grossAmount: "3000.00" } });
    const response = await api().get(`/hr/payroll/${legacy.id}`);
    expect(response.status).toBe(200);
    expect(response.body.policy.version).toBe(0);
    expect(response.body.lines[0]).toMatchObject({ baseSalary: "3000.00", validatedHours: "8.00", automaticAmount: "3000.00", grossAmount: "3000.00" });
    for (const field of ["attendanceHours", "regularHours", "overtimeHours", "hourlyRate"]) expect(response.body.lines[0]).not.toHaveProperty(field);
    const exported = await api().get(`/hr/payroll/${legacy.id}/employees/${employeeId}/export.pdf`);
    expect(exported.status).toBe(200);
    expect(exported.headers["content-type"]).toContain("application/pdf");
  });
  it.each(["COMPLETED", "CANCELLED"] as const)("refuses attendance replacement on a %s project and preserves the draft", async (status) => {
    const project = await createStartedProject(harness, tenant);
    const employee = await api().post("/hr/employees", { firstName: "Import", lastName: status, jobTitle: "Technicien", hireDate: "2026-01-01", contractType: "PERMANENT" });
    expect(employee.status).toBe(201);
    const employeeId = employee.body.id;
    for (const [type, occurredAt] of [["IN", "2026-09-14T08:00:00Z"], ["OUT", "2026-09-14T16:00:00Z"]]) {
      expect((await api().post("/hr/attendance", { employeeId, projectId: project.projectId, type, occurredAt })).status).toBe(201);
    }
    const sheet = await api().post("/hr/timesheets", { employeeId, weekStart: "2026-09-14" });
    expect(sheet.status).toBe(201);
    const draft = await api().put(`/hr/timesheets/${sheet.body.id}/entries`, { entries: [{ workDate: "2026-09-14", hours: "3.25", projectId: project.projectId, wbsItemId: project.leafId, description: "Saisie à conserver" }] });
    expect(draft.status).toBe(200);
    expect((await api().post(`/projects/${project.projectId}/status`, { status, ...(status === "CANCELLED" ? { reason: "Chantier annulé" } : {}) })).status).toBe(201);

    const rejected = await api().post(`/hr/timesheets/${sheet.body.id}/from-attendance`, { replaceExisting: true });
    expect(rejected.status).toBe(400);
    const preserved = await api().get(`/hr/timesheets/${sheet.body.id}`);
    expect(preserved.status).toBe(200);
    expect(preserved.body.status).toBe("DRAFT");
    expect(preserved.body.totalHours).toBe("3.25");
    expect(preserved.body.entries).toEqual(draft.body.entries);
    expect(await harness.prisma.auditLog.count({ where: { organizationId: tenant.organizationId, action: "hr.timesheet.attendance_imported", resourceId: sheet.body.id } })).toBe(0);
  });
});
